# Generated by Django 3.1.6 on 2021-02-14 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musics',
            name='likes',
            field=models.ManyToManyField(related_name='music_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
