# Generated by Django 3.1.6 on 2021-02-15 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_musics_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='likes',
            field=models.ManyToManyField(related_name='books_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
