# Generated by Django 3.1.6 on 2021-02-19 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_books_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apple_mes_users',
            field=models.ManyToManyField(related_name='apple_mes_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
