# Generated by Django 3.1.6 on 2021-02-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_profile_apple_mes_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloud_profile', to='polls.profile')),
            ],
        ),
    ]
