# Generated by Django 3.1.6 on 2021-02-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210223_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='file_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
