# Generated by Django 3.1.6 on 2021-02-27 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_cloud_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='cloud_posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_cloud', to='polls.profile_images')),
            ],
        ),
    ]
