# Generated by Django 3.1.6 on 2021-02-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_cloud_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_images',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
