# Generated by Django 3.1.6 on 2021-02-27 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_profile_images_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud_posts',
            name='profile_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_cloud', to='polls.profile_images'),
        ),
        migrations.AlterField(
            model_name='cloud_posts',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloud_post_profile', to='polls.profile'),
        ),
    ]
