# Generated by Django 3.1.6 on 2021-02-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_artist_favorite_genre_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
    ]
