# Generated by Django 3.1.6 on 2021-03-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_frank',
            field=models.ManyToManyField(related_name='profile_images_rank', to='polls.profile_images'),
        ),
    ]
