# Generated by Django 3.1.6 on 2021-03-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_profile_my_frank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes_count_pr',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
