# Generated by Django 3.1.6 on 2021-03-07 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_playlist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist_init',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=200)),
                ('poster', models.FileField(upload_to='')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_post_i_profile', to='polls.profile')),
            ],
        ),
    ]
