# Generated by Django 3.1.6 on 2021-03-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_playlist_init'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='name',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Playlist_init_profile', to='polls.playlist_init'),
        ),
    ]
