# Generated by Django 3.1.6 on 2021-03-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20210307_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist_init',
            name='defoult_playlist',
            field=models.BooleanField(default=False),
        ),
    ]
