# Generated by Django 3.1.6 on 2021-03-10 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20210309_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.FileField(upload_to='')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_post_profile', to='polls.profile')),
            ],
        ),
    ]
