# Generated by Django 3.1.6 on 2021-03-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_courses_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses_profile',
            old_name='poster',
            new_name='video',
        ),
        migrations.CreateModel(
            name='my_channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('poster', models.FileField(upload_to='')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ch_post_profile', to='polls.profile')),
            ],
        ),
        migrations.AddField(
            model_name='courses_profile',
            name='my_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_channel_post_profile', to='polls.my_channel'),
        ),
    ]
