# Generated by Django 3.1.6 on 2021-03-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20210312_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_profile',
            name='likes',
            field=models.ManyToManyField(related_name='likes_videos', to='polls.Profile'),
        ),
        migrations.AddField(
            model_name='my_channel',
            name='subscribe',
            field=models.ManyToManyField(to='polls.Profile'),
        ),
    ]
