# Generated by Django 3.1.6 on 2021-03-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20210313_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_channel',
            name='main_poster',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
