# Generated by Django 3.1.6 on 2021-03-22 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_auto_20210322_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='pr_time_pr_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.pr_time')),
                ('profile_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.profile_images')),
            ],
        ),
    ]
