# Generated by Django 3.1.6 on 2021-03-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_pr_time_pr_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr_time_pr_images',
            name='times',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
