# Generated by Django 3.1.6 on 2021-04-19 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_auto_20210414_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=400)),
                ('courses_profile_v', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_profile_v', to='polls.courses_profile')),
                ('likes', models.ManyToManyField(related_name='likes_videos_com', to='polls.Profile')),
                ('profile_com', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_com', to='polls.profile')),
            ],
        ),
    ]
