# Generated by Django 3.1.6 on 2021-05-05 18:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_comments_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ads_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(default='', max_length=400)),
                ('min_auditory', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_auditory', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('Category', models.CharField(choices=[('Sport', 'Sport'), ('Travel', 'Travel'), ('Games', 'Games'), ('Download_App', 'Download App')], default='Sport', max_length=39)),
                ('budget', models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(2)])),
                ('categories', models.ManyToManyField(related_name='profile_catgory_p_two', to='polls.profile_catgory')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_executor', to='polls.profile')),
                ('profile_ads_m', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_ads_m', to='polls.profile')),
                ('views', models.ManyToManyField(related_name='views_ads', to='polls.Profile')),
            ],
        ),
    ]
