# Generated by Django 3.1.6 on 2021-05-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_ads_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads_manager',
            name='Category',
            field=models.CharField(choices=[('Music', 'Music'), ('Profile', 'Profile'), ('Product', 'Product'), ('Download_App', 'Download App')], default='Music', max_length=39),
        ),
    ]
