# Generated by Django 3.1.6 on 2021-05-29 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_auto_20210505_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_manager',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='ads_tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.ads_manager')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_executor_p', to='polls.profile')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.profile')),
            ],
        ),
    ]
