# Generated by Django 3.1.6 on 2021-05-30 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0043_auto_20210529_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ads_tasks_executor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_tasks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.ads_tasks')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.profile')),
            ],
        ),
    ]
