# Generated by Django 3.1.6 on 2021-06-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0044_ads_tasks_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_tasks_executor',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
