# Generated by Django 3.1.6 on 2021-06-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_ads_tasks_executor_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ads_tasks_executor',
            new_name='ads_tasks_executor_post',
        ),
    ]
