# Generated by Django 3.1.6 on 2021-06-13 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_auto_20210601_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_manager',
            name='set_auditory',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
