# Generated by Django 3.1.6 on 2021-06-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0047_ads_manager_set_auditory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads_manager',
            name='set_auditory',
        ),
        migrations.AddField(
            model_name='ads_manager',
            name='likes',
            field=models.ManyToManyField(related_name='likes_ads', to='polls.Profile'),
        ),
    ]
