# Generated by Django 3.1.6 on 2021-06-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0049_ads_tasks_executor_post_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads_tasks_executor_post',
            name='times',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
