# Generated by Django 3.1.6 on 2021-06-28 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0053_invite_users_user_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite_users',
            name='user_n',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_invaite', to=settings.AUTH_USER_MODEL),
        ),
    ]
