# Generated by Django 3.1.6 on 2021-07-22 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0060_profile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
