# Generated by Django 3.1.6 on 2021-08-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0062_cloud_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloud',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
