# Generated by Django 3.1.6 on 2021-08-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0063_auto_20210802_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
