# Generated by Django 3.1.6 on 2021-08-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0066_profile_cloud_size_my_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cloud_size_max_value_my_plan',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
