# Generated by Django 3.1.6 on 2021-08-06 15:48

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0067_profile_cloud_size_max_value_my_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_id', models.TextField()),
                ('title', models.CharField(max_length=200, verbose_name='Song_name')),
                ('description', models.TextField()),
                ('song', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created_At')),
                ('likes', models.ManyToManyField(related_name='Song_kpost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
