# Generated by Django 3.1.6 on 2021-08-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0068_song_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='status_x',
            field=models.CharField(default='True', max_length=6),
        ),
        migrations.AddField(
            model_name='song_res',
            name='status_x',
            field=models.CharField(default='True', max_length=6),
        ),
    ]
