# Generated by Django 3.1.6 on 2021-08-12 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0070_auto_20210807_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='song1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_res_is_fav', to='polls.song_res'),
        ),
    ]
