# Generated by Django 3.1.6 on 2021-08-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0072_books_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='status_x',
            field=models.CharField(default='True', max_length=6),
        ),
    ]
