# Generated by Django 3.1.6 on 2021-08-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0074_books_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist_init',
            name='song_res',
            field=models.ManyToManyField(related_name='songs_res', to='polls.Song_res'),
        ),
    ]
