# Generated by Django 3.1.6 on 2021-08-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0075_playlist_init_song_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='myresiver',
            field=models.ManyToManyField(related_name='profile_res_my', to='polls.Profile'),
        ),
    ]
